baseurl = "http://next.rebeccameier.ch/"

title = "Rebecca Meier | Graphiste | La Chaux-de-Fonds"
copyright = "© 2018 Rebecca Meier"

googleAnalytics = "UA-55649932-1"

enableRobotsTXT = true

DefaultContentLanguage = "fr"

[Languages]
[Languages.fr]
weight = 1
title = "Rebecca Meier | Graphiste | La Chaux-de-Fonds"
languageName = "Français"
[[Languages.fr.menu.top_menu]]
url = "/fr/"
name = "Accueil"
weight = -10
[Languages.fr.params]
description = "Rebecca Meier, graphiste à la Chaux-de-Fonds, mes prestations se divisent en trois groupes; identité visuelle, design graphique et création de visuels."

[Languages.en]
weight = 2
title = "Rebecca Meier | Graphic designer | La Chaux-de-Fonds"
languageName = "English"
[[Languages.en.menu.top_menu]]
url = "/en/"
name = "Home"
weight = -10
[Languages.en.params]
description = "Rebecca Meier, graphic designer at La Chaux-de-Fonds, my services are divided in three groups; corporate identity, editorial design and visual creation."

[params]
author = "Rebecca Meier"
titleFollow = "| Rebecca Meier"
keywords = [ "graphiste", "graphic designer", "la chaux-de-fonds", "rebecca meier", "rebecca", "meier", "rebekah", "rebekka", "rebbeca", "rebeca", "meyer", "mayer", "maier", "graphisme", "graphiste", "freelance", "entreprise de graphisme", "atelier de création", "contemporain", "essentiel", "typographie", "typographe", "polygraphe", "artiste", "professionnel", "entreprise", "agence de communication", "graphic design", "designer", "neuchâtel", "la chaux-de-fonds", "la chaux de fonds", "neuch", "montagnes", "neuchateloises", "littoral", "création logos", "logo", "freelance", "indépendante", "haut", "travaux graphiques", "corporate", "corporate identity", "conception graphique", "campagne", "identité visuelle", "essentiel", "simplicité", "typo", "style épuré", "style feminin", "communication visuelle", "atelier de communication", "atelier de graphisme", "graphiste", "la chaux-de-fonds", "portfolio", "travaux", "création", "logo", "flyer", "brochure", "dépliant" ]
