baseurl = "http://next.rebeccameier.ch/"

title = "Rebecca Meier | Graphiste | Canton de Neuchâtel"
copyright = "© 2025 Rebecca Meier"

googleAnalytics = "UA-55649932-1"

enableRobotsTXT = true

DefaultContentLanguage = "fr"

disableKinds = ["taxonomy","taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Languages]
[Languages.fr]
weight = 1
title = "Rebecca Meier | Graphiste | Canton de Neuchâtel"
languageName = "Français"
[Languages.fr.params]
description = "Rebecca Meier, graphiste basée à Chézard-St-Martin, Neuchâtel (Suisse) mes prestations graphiques se divisent en trois groupes; identité visuelle, design graphique et création de visuels. Ma pratique artistique est orientée sur la collaboration étroite avec le client et une reflexion conceptuelle pour répondre à ses besoins au mieux. En outre, forte d'une expérience dans la coordination de projets, je mets au service ces compétences en parallèle pour une communication efficiente dès la prise de décision. Enfin, pour le plaisir de transmettre, je garde un pied dans l'enseignement du dessin artistique."

[Languages.en]
weight = 2
title = "Rebecca Meier | Graphic designer | Canton de Neuchâtel"
languageName = "English"
[Languages.en.params]
description = "Rebecca Meier, graphic designer based in Chézard-St-Martin, Neuchâtel (Switzerland) my graphic design services are divided in three groups; corporate identity, editorial design and visual creation. My artistic work involves close collaboration with the client and conceptual research to respond his needs at best.In addition, my experience in project coordination, allows me to use these skills in combination to ensure efficient communication right from the decision-making stage. Finally, for the pleasure of passing on my knowledge, I keep a foot in teaching artistic drawing."

[params]
author = "Rebecca Meier"
titleFollow = "| Rebecca Meier"
keywords = [ "graphiste", "graphic designer","graphic design", "la chaux-de-fonds", "rebecca meier", "rebecca", "meier", "rebekah", "rebekka", "rebbeca", "rebeca", "meyer", "mayer", "maier", "graphisme", "graphiste", "freelance", "entreprise de graphisme", "atelier de création", "contemporain", "essentiel", "typographie", "typographe", "polygraphe", "artiste", "professionnel", "entreprise", "agence de communication", "graphic design", "designer", "neuchâtel", "la chaux-de-fonds", "la chaux de fonds", "neuch", "montagnes", "neuchateloises", "littoral", "création logos", "logo", "freelance", "indépendante", "haut", "travaux graphiques", "corporate", "corporate identity", "conception graphique", "campagne", "identité visuelle", "essentiel", "simplicité", "typo", "style épuré", "style feminin", "communication visuelle", "atelier de communication", "atelier de graphisme", "graphiste", "la chaux-de-fonds","val-de-ruz", "chezard", "portfolio", "travaux", "création", "logo", "flyer", "brochure", "dépliant","communication", "suisse", "romandie", "cartes", "carte de visite", "packaging", "création graphique", "papier à lettre", "depliant", "affiche", "mise en page", "livre", "journal", "magazine", "édition", "revue", "concept", "pub", "présentation d'entreprise", "panneau", "bâche", "vitrine", "enseinge", "véhicule", "display", "support", "signalétique", "autocollant", "prospectus", "traitement typographique", "charte", "grille modulaire", "illustration", "dessin", "drawing", "coordination", "projet", "project", "organisation" ]
