baseurl = "http://next.rebeccameier.ch/"
languageCode = "fr-ch"
title = "Rebecca Meier | Graphiste | La Chaux-de-Fonds"
theme = "rebeccameier-theme"
copyright = "© 2016 Rebecca Meier"

[params]
  ContentLanguages = [
    "fr",
    "en"
  ]
